name = "pb-pastekan-paste"
type = "javascript"

account_id = "4f2534559b938e661168af847419a63e"
workers_dev = true
zone_id = "3f3844b6e82b8efa1080436ffcd07e94"
webpack_config = "webpack.config.js"

kv_namespaces = [
  { binding = "paste", id = "0ac85811a1b1437e924b94eb029abca6", preview_id = "3cb479362cec4314b6bfb5181aad3309" },
]

[build]
command = "yarn install && yarn build"

[build.upload]
format = "service-worker"
